  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: mongodb
    namespace: qflamarion
    labels:
      app: mongodb
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: mongodb
    template:
      metadata:
        labels:
          app: mongodb
      spec:
        containers:
          - name: mongodb
            image: mongo:4.4
            ports:
              - containerPort: 27017
            livenessProbe:
              tcpSocket:
                port: 27017
              initialDelaySeconds: 10
              periodSeconds: 10
              failureThreshold: 3
            resources:
              requests:
                memory: "100Mi"
                cpu: "100m"
              limits:
                memory: "200Mi"
                cpu: "200m"

  ---
  apiVersion: v1
  kind: Service
  metadata:
    name: mongodb-service
    namespace: qflamarion
  spec:
    type: ClusterIP
    selector:
      app: mongodb
    ports:
      - protocol: TCP
        port: 27017
        targetPort: 27017
