apiVersion: apps/v1
kind: Deployment
metadata:
  name: webnodb
  namespace: qflamarion
  labels:
    app: webnodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webnodb
  template:
    metadata:
      labels:
        app: webnodb
    spec:
      containers:
        - name: webnodb
          image: quentinfl/flask-simple:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: webnodb-service
  namespace: qflamarion
spec:
  selector:
    app: webnodb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
