version: "3.8"

services:
  flask_app_db:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask_app_db
    ports:
      - "5001:5000"
    networks:
      - app_network
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017/"

  flask_app_no_db:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask_app_no_db
    environment:
      NO_DB: "true"
    ports:
      - "5002:5000"
    networks:
      - app_network

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app_network

networks:
  app_network:
